import {
  profile,
  user1,
  user2,
  user3,
  user4,
  user5,
  user6,
  user7,
  user8,
  user9,
} from "../../assets/images"

export const chatData = [
  {
    id: 1,
    name: "Betty",
    imgUrl: user1,
    age: 32,
    isOnline: true,
    lastMessage:
      "That sounds like a lot of fun. Would you like to go together sometime?",
    timeSent: "5 mins",
  },
  {
    id: 2,
    name: "Basquit",
    imgUrl: user2,
    age: 28,
    isOnline: false,
    lastMessage: "Sure, let's do that. When are you free?",
    timeSent: "10 mins",
  },
  {
    id: 3,
    name: "Oliver",
    imgUrl: user3,
    age: 30,
    isOnline: true,
    lastMessage: "Sounds like a plan! Let's make it happen.",
    timeSent: "25 mins",
  },
  {
    id: 4,
    name: "Sophie",
    imgUrl: user9,
    age: 27,
    isOnline: true,
    lastMessage: "Definitely! Looking forward to it.",
    timeSent: "30 mins",
  },

  {
    id: 5,
    name: "William",
    imgUrl: user5,
    age: 29,
    isOnline: false,
    lastMessage: "Let me check my schedule and get back to you.",
    timeSent: "35 mins",
  },
]

export const datesData = [
  {
    id: 1,
    imgUrl: user1,
    name: "Dianna",
    lastName: "Jones",
    age: 25,
    city: "New York",
    country: "USA",
  },
  {
    id: 2,
    imgUrl: user2,
    name: "Jane",
    lastName: "Smith",
    age: 28,
    city: "Los Angeles",
    country: "USA",
  },
  {
    id: 3,
    imgUrl: user3,
    name: "Chiara",
    lastName: "Doe",
    age: 26,
    city: "London",
    country: "UK",
  },
  {
    id: 4,
    imgUrl: user4,
    name: "Ella",
    lastName: "Williams",
    age: 29,
    city: "Sydney",
    country: "Australia",
  },
  {
    id: 5,
    imgUrl: user5,
    name: "Jullie",
    lastName: "Brown",
    age: 30,
    city: "Paris",
    country: "France",
  },
  {
    id: 6,
    imgUrl: user6,
    name: "Olivia",
    lastName: "Miller",
    age: 27,
    city: "Berlin",
    country: "Germany",
  },
  {
    id: 7,
    imgUrl: user7,
    name: "William",
    lastName: "Wilson",
    age: 31,
    city: "Toronto",
    country: "Canada",
  },
  {
    id: 8,
    imgUrl: user8,
    name: "Sophia",
    lastName: "Moore",
    age: 29,
    city: "Tokyo",
    country: "Japan",
  },
  {
    id: 9,
    imgUrl: user9,
    name: "Diana",
    lastName: "Taylor",
    age: 32,
    city: "Mumbai",
    country: "India",
  },
]

export const profileData = [
  {
    name: "Jacob Jones",
    age: 30,
    imgUrl: profile,
    hobbies: ["Hiking", "Photography", "Cooking"],
    bio: "I'm an adventurous person who loves exploring new places, trying out different cuisines, capturing moments through photography, and spending time in nature. I enjoy hiking on weekends and experimenting with new recipes in the kitchen. Traveling and experiencing different cultures are some of my greatest passions, and I'm always looking for my next adventure.",
  },
]
